// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrDjgLcpL8QFEFmXbAgs73smTvWlWSiDk',
    appId: '1:388071341128:web:8688a3af1e824129e82c7d',
    messagingSenderId: '388071341128',
    projectId: 'rent-car-app-dcc7f',
    authDomain: 'rent-car-app-dcc7f.firebaseapp.com',
    storageBucket: 'rent-car-app-dcc7f.firebasestorage.app',
    measurementId: 'G-F3EZL4GGZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYG-g5sSSmi8tQOkHqwz8ICwaryFFaBx0',
    appId: '1:388071341128:android:eb34b111732ad37be82c7d',
    messagingSenderId: '388071341128',
    projectId: 'rent-car-app-dcc7f',
    storageBucket: 'rent-car-app-dcc7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrFCoGBf84DPkDDQbhG84-pXKezak0PIg',
    appId: '1:388071341128:ios:9f1c84b9419721cbe82c7d',
    messagingSenderId: '388071341128',
    projectId: 'rent-car-app-dcc7f',
    storageBucket: 'rent-car-app-dcc7f.firebasestorage.app',
    iosBundleId: 'com.example.rentCarsApp',
  );
}
